#!/bin/bash
git diff $(git branch --all | fzf --prompt "Select first branch: " --bind 'j:down,k:up,ctrl-f:preview-down,ctrl-b:preview-up') $(git branch --all | fzf --prompt "Select second branch: " --bind 'j:down,k:up,ctrl-f:preview-down,ctrl-b:preview-up')

