#!/bin/bash
git log --oneline | fzf --bind 'j:down,k:up,ctrl-f:preview-down,ctrl-b:preview-up' --preview 'git show --color=always $(echo {} | cut -d" " -f1)' --bind 'enter:execute:git show --color=always $(echo {} | cut -d" " -f1) | less -R'

